export const transactionsData = [
  {
    id: '1',
    type: 'debit',
    title: 'Money Sent',
    time: 'Just now',
    amount: 100000,
    icon: 'send',
  },
  {
    id: '2',
    type: 'credit',
    title: 'Money Received',
    time: '2 mins ago',
    amount: 50000,
    icon: 'receive',
  },
  {
    id: '3',
    type: 'debit',
    title: 'Airtime Purchase',
    time: '10 mins ago',
    amount: 2000,
    icon: 'airtime',
  },
  {
    id: '4',
    type: 'credit',
    title: 'Salary Payment',
    time: '1 hour ago',
    amount: 250000,
    icon: 'receive',
  },
  {
    id: '5',
    type: 'debit',
    title: 'Utility Bill',
    time: '2 hours ago',
    amount: 12000,
    icon: 'send',
  },
  {
    id: '6',
    type: 'debit',
    title: 'Groceries',
    time: '3 hours ago',
    amount: 4500,
    icon: 'send',
  },
  {
    id: '7',
    type: 'credit',
    title: 'Refund Received',
    time: 'Yesterday',
    amount: 7000,
    icon: 'receive',
  },
  {
    id: '8',
    type: 'debit',
    title: 'Movie Tickets',
    time: 'Yesterday',
    amount: 1500,
    icon: 'send',
  },
  {
    id: '9',
    type: 'credit',
    title: 'Cashback',
    time: '2 days ago',
    amount: 200,
    icon: 'receive',
  },
  {
    id: '10',
    type: 'debit',
    title: 'Restaurant Payment',
    time: '2 days ago',
    amount: 5000,
    icon: 'send',
  },
  {
    id: '11',
    type: 'debit',
    title: 'Online Shopping',
    time: '3 days ago',
    amount: 22000,
    icon: 'send',
  },
  {
    id: '12',
    type: 'credit',
    title: 'Freelance Payment',
    time: '3 days ago',
    amount: 120000,
    icon: 'receive',
  },
];